### ISSUE TITLE
jQuery Not Found

### ISSUE THREAD

**Issue by nathanielhudson** [FrazerSeymour/flip#24]
GET file:///Users/nathanielhudson/Documents/flip/node_modules/jquery/dist/jquery.min.js net::ERR_FILE_NOT_FOUND

![screen shot 2016-08-30 at 8 41 27 pm](https://cloud.githubusercontent.com/assets/2744848/18112007/4cdc1028-6ef2-11e6-9dec-a63a2164dd3a.png)

@FrazerSeymour : looks like an issue w/ the node modules thing

**Comment by nathanielhudson** [comment]
Ah shoot. Didn't realize deps had changed. My bad.

**Comment by FrazerSeymour** [comment]
I'm guessing you needed to `npm install`?

**Comment by nathanielhudson** [comment]
yep. I am dumb.
