### ISSUE TITLE
Server up

### ISSUE THREAD

**Issue by nathanielhudson** [FrazerSeymour/flip#3]

**Comment by nathanielhudson** [comment]
Okay, the server runs and can self-update. The update script probably kills all active sockets, since it relaunches the app, but yolo. It also has no auth on it, so you could potentially dos my server with it (but i think the risk is pretty low). Once we have working config files we could add a secret key to it.

**Comment by FrazerSeymour** [comment]
The former should be added as a bug (or feature, I'm not sure the difference between the two at the moment). Config files too as another. What socket _should_ they be going through? (_That_ should be in config.)

**Comment by nathanielhudson** [comment]
Okay, I've created issues for the above (#20, #21). Server works now! David and I sent burritos at each other.

**Comment by FrazerSeymour** [comment]
Do we want to close this?

**Comment by nathanielhudson** [comment]
I guess so!
